services:
  nmap-api:
    container_name: nmapi
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    build: .
    image: nmapi
    environment:
      - SCAN_TARGET=192.168.1.0/24
      - SCAN_INTERVAL_HOURS=12
    restart: unless-stopped
    
