services:
  nmap-api:
    build: .
    image: nmap-simple-api
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    environment:
      - SCAN_TARGET=localhost
